# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Restore artifacts, or setup vcpkg
      uses: lukka/run-vcpkg@v6
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgTriplet: x64-windows
        vcpkgArguments: '@${{ github.workspace }}/vcpkg.txt'

    # Runs a single command using the runners shell
    - name: List installed
      run: |
        Write-Host (dir ${{ github.workspace }}/vcpkg/installed)
      
