name: Build OpenCV x64-windows

#on: [push]
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore artifacts, or setup vcpkg
      uses: lukka/run-vcpkg@v6
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgTriplet: x64-windows
        vcpkgArguments: '@${{ github.workspace }}/vcpkg.txt'

    - name: Configure CMake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/opencv/CMakeLists.txt'
        buildDirectory: ${{ github.workspace }}/build
        useVcpkgToolchainFile: true
        buildWithCMake: false
        cmakeAppendedArgs: >
          '
          -G "Visual Studio 16 2019"
          -A "x64"
          -DMAKE_BUILD_TYPE=RELEASE
          -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/OpenCV"
          -DWITH_EIGEN=ON
          -DWITH_TBB=ON
          -DWITH_OPENGL=ON
          -DBUILD_TIFF=ON
          -DWITH_QT=OFF
          -DWITH_FFMPEG=OFF
          -DBUILD_opencv_apps=OFF
          -DBUILD_DOCS=OFF
          -DBUILD_PACKAGE=OFF
          -DBUILD_PERF_TESTS=OFF
          -DBUILD_TESTS=OFF
          -DBUILD_JAVA=OFF
          -DBUILD_opencv_python2=OFF
          -DBUILD_opencv_python3=OFF
          -DBUILD_LIST="imgcodecs,imgproc,highgui"
          -DBUILD_opencv_world=ON
          '

    # - name: Configure CMake
    #   working-directory: ${{github.workspace}}/opencv-4.5.1
    #   env:
    #     OpenBLAS_HOME: ${{github.workspace}}\OpenBLAS
    #   run: >
    #       cmake 
    #       -B ${{github.workspace}}/opencv-4.5.1/build
    #       -DMAKE_BUILD_TYPE=RELEASE
    #       -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/OpenCV"
    #       -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
    #       -G "Visual Studio 16 2019"
    #       -A "x64"
    #       -DWITH_EIGEN=ON
    #       -DWITH_TBB=ON
    #       -DWITH_OPENGL=ON
    #       -DBUILD_TIFF=ON
    #       -DWITH_QT=OFF
    #       -DWITH_FFMPEG=OFF
    #       -DBUILD_opencv_apps=OFF
    #       -DBUILD_DOCS=OFF
    #       -DBUILD_PACKAGE=OFF
    #       -DBUILD_PERF_TESTS=OFF
    #       -DBUILD_TESTS=OFF
    #       -DBUILD_JAVA=OFF
    #       -DBUILD_opencv_python2=OFF
    #       -DBUILD_opencv_python3=OFF
    #       -DBUILD_LIST="imgcodecs,imgproc,highgui"
    #       -DBUILD_opencv_world=ON

    # - name: Build
    #   working-directory: ${{github.workspace}}/opencv-4.5.1
    #   run: |
    #     msbuild build\OpenCV.sln /t:Build /p:Configuration=Release
    #     msbuild build\INSTALL.vcxproj /t:Build /p:Configuration=Release

    # - name: Pack
    #   working-directory: ${{github.workspace}}
    #   run: |
    #     Copy-Item vcpkg\installed\x64-windows\bin\tbb.dll OpenCV\x64\vc16\bin\
    #     Copy-Item OpenBLAS\bin\libopenblas.dll OpenCV\x64\vc16\bin\
    #     Write-Host (dir OpenCV\x64\vc16\bin\)
