name: Build OpenCV x64-windows

#on: [push]
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download OpenBLAS
      working-directory: ${{github.workspace}}
      run: |
        Invoke-WebRequest https://github.com/xianyi/OpenBLAS/releases/download/v0.3.13/OpenBLAS-0.3.13-x64.zip -O OpenBLAS.zip
        Write-Host ('OpenBLAS downloaded')
        Expand-Archive .\OpenBLAS.zip .\OpenBLAS
        Write-Host ('OpenBLAS unpacked')
        Copy-Item .\OpenBLAS\lib\libopenblas.lib .\OpenBLAS\lib\openblas.lib

    - name: Download OpenCV
      working-directory: ${{github.workspace}}
      run: |
        Invoke-WebRequest https://github.com/opencv/opencv/archive/4.5.1.zip -O opencv.zip
        Write-Host ('OpenCV downloaded')
        Expand-Archive .\opencv.zip .
        Write-Host ('OpenCV unpacked')

    - name: Prepare vcpkg
      uses: lukka/run-vcpkg@v6
      id: runvcpkg
      with:
        vcpkgArguments: eigen3 tbb
        vcpkgDirectory: ${{github.workspace}}/vcpkg
        vcpkgGitCommitId: 0bf3923f9fab4001c00f0f429682a0853b5749e0
        vcpkgTriplet: x64-windows
        appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}

    - name: Configure CMake
      working-directory: ${{github.workspace}}/opencv-4.5.1
      env:
        OpenBLAS_HOME: ${{github.workspace}}\OpenBLAS
      run: |
          cmake 
            -S ${{github.workspace}}/opencv-4.5.1 \
            -B ${{github.workspace}}/opencv-4.5.1/build \
            -DMAKE_BUILD_TYPE=RELEASE \
            -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/OpenCV" \
            -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -G "Visual Studio 16 2019" \
            -A "x64" \
            -DWITH_EIGEN=ON \
            -DWITH_TBB=ON \
            -DWITH_OPENGL=ON \
            -DBUILD_TIFF=ON \
            -DWITH_QT=OFF \
            -DWITH_FFMPEG=OFF \
            -DBUILD_opencv_apps=OFF \
            -DBUILD_DOCS=OFF \
            -DBUILD_PACKAGE=OFF \
            -DBUILD_PERF_TESTS=OFF \
            -DBUILD_TESTS=OFF \
            -DBUILD_JAVA=OFF \
            -DBUILD_opencv_python2=OFF \
            -DBUILD_opencv_python3=OFF \
            -DBUILD_LIST="imgcodecs,imgproc,highgui" \
            -DBUILD_opencv_world=ON

    - name: Build
      working-directory: ${{github.workspace}}/opencv-4.5.1
      run: |
        msbuild build\OpenCV.sln /t:Build /p:Configuration=Release build\OpenCV.sln
        msbuild build\INSTALL.vcxproj /t:Build /p:Configuration=Release build\OpenCV.sln

    - name: Pack
      working-directory: ${{github.workspace}}
      run: |
        Copy-Item vcpkg\installed\x64-windows\bin\tbb.dll OpenCV\x64\vc16\bin\
        Copy-Item OpenBLAS\bin\libopenblas.dll OpenCV\x64\vc16\bin\
        dir OpenCV\x64\vc16\bin\
